# Generated by Django 3.2.12 on 2022-03-17 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_title', models.CharField(max_length=50)),
                ('courses_online', models.CharField(max_length=100)),
                ('course_video', models.CharField(max_length=8000)),
                ('course_mashaghel_link', models.CharField(blank=True, max_length=50, null=True)),
                ('courses_date', models.CharField(max_length=100)),
                ('courses_teacher_name', models.CharField(max_length=100)),
                ('course_teacher_rezume', models.CharField(max_length=100)),
                ('course_id', models.IntegerField()),
                ('course_time', models.IntegerField()),
                ('course_targets', models.CharField(max_length=1000)),
                ('course_sections', models.CharField(max_length=1000)),
                ('course_learning_manager', models.CharField(max_length=50)),
                ('course_contact_number_1', models.CharField(max_length=50)),
                ('course_contact_number_2', models.CharField(max_length=50)),
                ('course_whatsapp_number', models.CharField(blank=True, max_length=50, null=True)),
                ('course_category', models.CharField(blank=True, max_length=50, null=True)),
                ('course_image', models.CharField(blank=True, max_length=200, null=True)),
                ('course_link', models.CharField(blank=True, max_length=50, null=True)),
                ('course_writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
