# Generated by Django 4.0.3 on 2022-04-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_id_alter_course_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_teacher_rezume',
            field=models.CharField(max_length=1000),
        ),
    ]
