# Generated by Django 4.0.3 on 2022-04-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_teacher_rezume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_sections',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_targets',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_mashaghel_link',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_teacher_rezume',
            field=models.CharField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_time',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='courses_teacher_name',
            field=models.CharField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='course',
            name='courses_title',
            field=models.CharField(max_length=2000),
        ),
    ]
