# Generated by Django 4.0.3 on 2022-04-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_course_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_teacher_rezume',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courses_teacher_name',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
