# Generated by Django 4.0.3 on 2022-04-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
    ]
