# Generated by Django 4.0.1 on 2022-01-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_title', models.CharField(max_length=50)),
                ('courses_online', models.BooleanField()),
                ('course_video', models.CharField(max_length=200)),
                ('courses_date', models.CharField(max_length=100)),
                ('courses_teacher_name', models.CharField(max_length=100)),
                ('course_teacher_rezume', models.CharField(max_length=100)),
                ('course_id', models.IntegerField()),
                ('course_time', models.IntegerField()),
                ('course_targets', models.CharField(max_length=200)),
                ('course_sections', models.CharField(max_length=1000)),
                ('course_learning_manager', models.CharField(max_length=50)),
                ('course_contact_number_1', models.CharField(max_length=50)),
                ('course_contact_number_2', models.CharField(max_length=50)),
            ],
        ),
    ]
