# Generated by Django 4.0.1 on 2022-03-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='image',
            field=models.FileField(upload_to='', verbose_name='exel'),
        ),
    ]
