# Generated by Django 3.2.12 on 2022-03-14 10:49

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_first_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='image',
            field=models.FileField(upload_to=files.models.upload_image_path),
        ),
    ]
